---

- name: Create user
  ansible.builtin.import_tasks: create_user.yml

- name: Create local directory structure
  ansible.builtin.import_tasks: create_local_dir_structure.yml

- name: SSH key check
  ansible.builtin.import_tasks: ssh_key_check.yml

- name: Config local login scripts
  ansible.builtin.import_tasks: login_scripts.yml

- name: Install workstation packages
  ansible.builtin.import_tasks: install_packages.yml

- name: Install non-packaged software
  ansible.builtin.import_tasks: install_non_packaged_software.yml
