---

- name: WSL hostname
  ansible.builtin.import_tasks: wsl_hostname.yml

- name: Upgrade packages
  ansible.builtin.import_tasks: upgrade_packages.yml

- name: Install packages
  ansible.builtin.import_tasks: install_packages.yml

- name: Create ansible user
  ansible.builtin.import_tasks: ansible_user.yml

- name: Ansible pull cronjob
  ansible.builtin.import_tasks: ansible_pull_cronjob.yml
